name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Build binaries
        run: |
          # Linux AMD64
          GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o godev-linux-amd64

          # Linux ARM64
          GOOS=linux GOARCH=arm64 go build -ldflags="-s -w" -o godev-linux-arm64

          # macOS AMD64
          GOOS=darwin GOARCH=amd64 go build -ldflags="-s -w" -o godev-darwin-amd64

          # macOS ARM64 (Apple Silicon)
          GOOS=darwin GOARCH=arm64 go build -ldflags="-s -w" -o godev-darwin-arm64

          # Windows AMD64
          GOOS=windows GOARCH=amd64 go build -ldflags="-s -w" -o godev-windows-amd64.exe

      - name: Create checksums
        run: |
          sha256sum godev-* > checksums.txt

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            godev-linux-amd64
            godev-linux-arm64
            godev-darwin-amd64
            godev-darwin-arm64
            godev-windows-amd64.exe
            checksums.txt
          body_path: .github/release-template.md
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
